KEY_QUANTITY = 'quantity'
KEY_PRICE = 'price'
KEY_PRODUCT = 'product'
KEY_TOTAL_PRICE = 'total_price'
KEY_OVERRIDE = 'override'
KEY_ORDER_ID = 'order_id'
KEY_COUPON_ID = 'coupon_id'
KEY_PAYMENT_ORDER_NONCE = 'payment_method_nonce'

SENDER_EMAIL_ID = 'no_reply@eShop.com'
